MODE=0
CUDA_VISIBLE_DEVICES="1" python run_table_CT_finetuning.py \
    --output_dir=output \
    --model_name_or_path=~/projects/TURL/turl-pretrain-ddp-warmup-dedup/checkpoint-last \
    --model_type=CT \
    --do_train \
    --data_dir="~/turl-data" \
    --evaluate_during_training \
    --per_gpu_train_batch_size=20 \
    --per_gpu_eval_batch_size=20 \
    --gradient_accumulation_steps=2 \
    --learning_rate=5e-5 \
    --num_train_epochs=10 \
    --save_total_limit=5 \
    --seed=1 \
    --cache_dir=cache \
    --overwrite_output_dir \
    --config_name=~/projects/TURL/src/configs/table-base-config_v2.json \
    --save_steps=5000 \
    --logging_steps=1500 \
    --warmup_steps=5000 \
    --allow_tf32 \
    --mode=$MODE
